export const themes = {
  light: {
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    secondaryTextColor: '#6b7280',
    placeholderColor: '#9ca3af',
    headerBackground: '#ffffff',
    cardBackground: '#ffffff',
    inputBackground: '#f3f4f6',
    buttonBackground: '#f3f4f6',
    borderColor: '#e5e7eb',
    primaryColor: '#3b82f6',
    iconColor: '#6b7280',
    tagBackground: '#dbeafe',
    tagTextColor: '#1e40af',
    warningBackground: '#fecaca',
    warningTextColor: '#b91c1c',
  },
  dark: {
    backgroundColor: '#1f2937',
    textColor: '#f9fafb',
    secondaryTextColor: '#d1d5db',
    placeholderColor: '#9ca3af',
    headerBackground: '#374151',
    cardBackground: '#374151',
    inputBackground: '#4b5563',
    buttonBackground: '#4b5563',
    borderColor: '#6b7280',
    primaryColor: '#60a5fa',
    iconColor: '#d1d5db',
    tagBackground: '#1e40af',
    tagTextColor: '#bfdbfe',
    warningBackground: '#b91c1c',
    warningTextColor: '#fecaca',
  },
  black: {
    backgroundColor: '#000000',
    textColor: '#ffffff',
    secondaryTextColor: '#a0a0a0',
    placeholderColor: '#808080',
    headerBackground: '#0a0a0a',
    cardBackground: '#0a0a0a',
    inputBackground: '#1a1a1a',
    buttonBackground: '#1a1a1a',
    borderColor: '#333333',
    primaryColor: '#64b5f6',
    iconColor: '#a0a0a0',
    tagBackground: '#0d47a1',
    tagTextColor: '#bbdefb',
    warningBackground: '#b71c1c',
    warningTextColor: '#ffcdd2',
  },
};
